#! /usr/bin/env bash

set -euo pipefail

DIR="$(realpath -- "$(dirname "${BASH_SOURCE[0]}")")"
GHDIR="$(realpath -- "$DIR/../")"

if [[ ! $# -eq 1 ]]; then 
  >&2 echo "Usage: $0 <branch-dir>"
  exit 1
fi

PRDIR="$(git -C "$1" rev-parse --show-toplevel)"

if [[ -e "$PRDIR/.envrc" || -e "$PRDIR/.vimrc" || -e "$PRDIR/.lockshaw.toml" ]]; then 
  >&2 echo "Error: $PRDIR already contains a .envrc or .vimrc or .lockshaw.toml"
  exit 1
fi

cat >"$PRDIR/.envrc" <<'EOF'
source_up_if_exists

use flake
EOF

cat >"$PRDIR/.vimrc" << 'EOF'
" example search path configuration
set path=lib/runtime/**,lib/**

" set build target
" let g:target = "pcg"

" set test target
" let g:test_target = "utils-test"
EOF
