#! /usr/bin/env bash

set -euo pipefail

DIR="$(realpath -- "$(dirname "${BASH_SOURCE[0]}")")"

info() {
  >&2 echo "$@"
}

error() {
  info "$@"
  exit 1
}

WORKTREE_EXTENSION='despreston/gh-worktree'
if ! (gh extension list 2>&1 | grep -q "$WORKTREE_EXTENSION"); then 
  info "Could not find worktree extension to gh-cli. Installing..."
  gh extension install "$WORKTREE_EXTENSION"
fi

if [[ $# -lt 1 || $# -gt 2 ]]; then 
  error "Usage: $0 <pr-number> [pr-alias]"
fi

ffpr() {
  if [[ ! -e $DIR/../pr/$1 ]]; then 
    cd "$DIR/../master"
    gh worktree pr "$1" ../pr/"$1"
  fi 
}

PRDIR="$(realpath -- "$DIR/../pr/$1")"
mkdir -p "$DIR/../pr"
if [[ ! -e "$PRDIR" ]]; then 
  if [[ $# -gt 2 && ! -e "$DIR/../$2" ]]; then 
    error "Alias $2 already exists"
  fi
  ffpr "$@"
  ff-install "pr/$1" 
  ln -s "$PRDIR" "$DIR/../$2"
else 
  ffpr "$@"
fi
for DEP in "$PRDIR/deps"/*; do 
  if [[ $(ls -1 "$DEP" | wc -l) -eq 0 ]]; then 
    "$DIR/ff-fix-submodules" "$PRDIR"
    break
  fi
done
echo cd "$DIR/../pr/$1"
