project_name = "flexflow"
cmake_require_shell = true
testsuite_macro = "FF_TEST_SUITE"
namespace_name = "FlexFlow"
header_extension = ".h"

build_targets = [
  "substitutions"
]
test_targets = [
  "substitutions-test"
]

[cmake_flags_extra]
FF_CUDA_ARCH = "60"
CUDA_PATH = "$(dirname $(which nvcc))/../"
CMAKE_CUDA_ARCHITECTURES = "60"
CMAKE_CUDA_COMPILER = "clang++" 
CMAKE_CUDA_HOST_COMPILER = "clang++"
